# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

# image: busybox

# pages:
#   stage: deploy
#   script:
#     - echo "The site will be deployed to $CI_PAGES_URL"
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# test:
#   script: go test -v ./test

stages:
  - test

test_job:
  stage: test
  tags:
    -  gitlab-org
  script:
    - echo "Testing..."
    - go test -v ./test