name: Go Tests

on: [push]

jobs:
  go_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23' # Замените на нужную версию Go

      - name: Run tests
        run: cd src && go test -v ./test